---
- name: Clear all firewall rules and recreate the winrm rules for Ansible
  hosts: windows
  gather_facts: false

  tasks:
    - name: Disable firewall
      win_firewall:
        state: disabled

    - name: Clear all firewall rules
      win_shell: |
        Get-NetFirewallRule | Remove-NetFirewallRule
      failed_when: false

    - name: Create firewall rule for winrm (HTTP)
      win_firewall_rule:
        name: '[Ansible] Allow WinRM HTTP (TCP-In)'
        localport: 5985
        remoteip: "{{ wsl2_ip | default('0.0.0.0/0') }}"
        protocol: tcp
        state: present
        enabled: true
        direction: in
        action: allow

    - name: Create firewall rule for winrm (HTTPS)
      win_firewall_rule:
        name: '[Ansible] Allow WinRM HTTPS (TCP-In)'
        localport: 5986
        remoteip: "{{ wsl2_ip | default('0.0.0.0/0') }}"
        protocol: tcp
        state: present
        enabled: true
        direction: in
        action: allow

    - name: Create firewall rule for mDNS (UDP)
      win_firewall_rule:
        name: "[Ansible] Allow mDNS (UDP-In)"
        localport: 5353
        protocol: udp
        enabled: true
        direction: in
        action: allow
        profiles:
          - private

    - name: Create firewall rule Wireless Display (TCP-In)
      win_firewall_rule:
        name: "[Ansible] Allow Wireless Display (TCP-In)"
        program: "%systemroot%\\system32\\WUDFHost.exe"
        enabled: true
        direction: in
        action: allow
        profiles:
          - private

    - name: Disable firewall block notifications
      win_shell: |
        Set-NetFirewallProfile -Profile Domain,Public,Private -NotifyOnListen False
      failed_when: false

    - name: Enable firewall
      win_firewall:
        state: enabled
