---
- name: Install Hyper-V and HostGuardian Service
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Hyper-V feature
      win_optional_feature:
        name: Microsoft-Hyper-V-All
        state: present

    - name: Install Host Guardian feature
      win_optional_feature:
        name: HostGuardian
        state: present
