---
- name: Install 1Password
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install 1Password
      win_chocolatey:
        name: 1password
        version: '7.9.835'
        state: present

    - name: Install 1Password CLI
      win_chocolatey:
        name: op
        version: '2.27.0'
        state: present
