---
- name: Install Docker Desktop
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Docker Desktop
      win_chocolatey:
        name: docker-desktop
        state: present

    - name: Configure .wslconfig
      win_copy:
        content: |
          [wsl2]
          memory=8GB
          processors=4
          swap=0
        dest: C:\Users\{{ ansible_user }}\.wslconfig
        force: true
