---
- name: Install Google Chrome
  hosts: windows
  gather_facts: false

  tasks:
    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        version: 119.0.6045.160
        state: present
